#!/usr/bin/env bash

source /setup_common.sh
source /decrypt_secrets.sh

if [ "$1" == "mix" ]; then
  exec "$@"
elif [ -n "$1" ]; then
  sh -c "$@"
else
  mix deps.get
  mix deps.compile
  mix compile
  mix release
  mix run --no-halt
fi
